tabs to spaces

diff --git a/share/scripts/oink-build b/share/scripts/oink-build
--- a/share/scripts/oink-build
+++ b/share/scripts/oink-build
@@ -13,11 +13,11 @@ autodie dodir "${OMIR_OINK_STATE_DIR}"
 
 # check release version early on
 if [ -e "${oink_statefile_rel}" ]; then
-	read oink_rel_saved < "${oink_statefile_rel}" || die
+    read oink_rel_saved < "${oink_statefile_rel}" || die
 
-	if [ -n "${oink_rel_saved}" ] && [ "${oink_rel}" != "${oink_rel_saved}" ]; then
-		die "OpenBSD release mismatch -- please nuke ${OMIR_OINK_BUILD_ROOT} and start over."
-	fi
+    if [ -n "${oink_rel_saved}" ] && [ "${oink_rel}" != "${oink_rel_saved}" ]; then
+        die "OpenBSD release mismatch -- please nuke ${OMIR_OINK_BUILD_ROOT} and start over."
+    fi
 fi
 
 # write release version we are building against to state file
@@ -26,20 +26,20 @@ printf '%s\n' "${oink_rel}" > "${oink_statefile_rel}" || die "Failed to create s
 
 # switch TMPDIR if configured
 if [ -n "${OMIR_OINK_TMPDIR-}" ]; then
-	autodie dodir "${OMIR_OINK_TMPDIR}" 1777
-	export TMPDIR="${OMIR_OINK_TMPDIR}"
+    autodie dodir "${OMIR_OINK_TMPDIR}" 1777
+    export TMPDIR="${OMIR_OINK_TMPDIR}"
 fi
 
 
 # populate build root
 if [ ! -e "${oink_statefile_have_src_unpacked}" ]; then
-	autodie oink_unpack_omir_tgz_to_build_root 'src.tar.gz'
-	autodie touch -- "${oink_statefile_have_src_unpacked}"
+    autodie oink_unpack_omir_tgz_to_build_root 'src.tar.gz'
+    autodie touch -- "${oink_statefile_have_src_unpacked}"
 fi
 
 if [ ! -e "${oink_statefile_have_sys_unpacked}" ]; then
-	autodie oink_unpack_omir_tgz_to_build_root 'sys.tar.gz'
-	autodie touch -- "${oink_statefile_have_sys_unpacked}"
+    autodie oink_unpack_omir_tgz_to_build_root 'sys.tar.gz'
+    autodie touch -- "${oink_statefile_have_sys_unpacked}"
 fi
 
 
@@ -57,16 +57,16 @@ rmfile "${oink_bdir_arch_ramdisk}/mr.fs"
 
 # create obj dir
 if [ -n "${oink_bdir_sys_arch_compile_ramdisk}" ]; then
-	autodie oink_make "${oink_bdir_sys_arch_compile_ramdisk}" obj
+    autodie oink_make "${oink_bdir_sys_arch_compile_ramdisk}" obj
 fi
 
 
 # hook: kconfig w/ default
 if [ -n "${oink_bdir_sys_arch_conf_ramdisk}" ]; then
-	autodie oink_run_hook kconfig - KCONF "${oink_bdir_sys_arch_conf_ramdisk}"
-	if [ ${oink_hook_did_run} -eq 0 ]; then
-		autodie oink_default_kconfig
-	fi
+    autodie oink_run_hook kconfig - KCONF "${oink_bdir_sys_arch_conf_ramdisk}"
+    if [ ${oink_hook_did_run} -eq 0 ]; then
+        autodie oink_default_kconfig
+    fi
 fi
 
 # hook: miniroot
@@ -75,7 +75,7 @@ autodie oink_run_hook miniroot "${oink_bdir_miniroot}"
 # hook: inject w/ default
 autodie oink_run_hook inject
 if [ ${oink_hook_did_run} -eq 0 ]; then
-	autodie oink_default_inject
+    autodie oink_default_inject
 fi
 # hook: inject-extra
 autodie oink_run_hook inject-extra
@@ -92,38 +92,38 @@ autodie oink_make "${oink_bdir_arch_ramdisk}"
 
 # publish to mirror if configured
 if \
-	[ "${OMIR_OINK_LOCAL_PUBLISH:-0}" -eq 1 ] && \
-	[ -n "${OMIR_OINK_LOCAL_PUBLISH_DIR-}" ]
+    [ "${OMIR_OINK_LOCAL_PUBLISH:-0}" -eq 1 ] && \
+    [ -n "${OMIR_OINK_LOCAL_PUBLISH_DIR-}" ]
 then
-	# OpenBSD/<rel>/<arch>/oink
-	publish_dir="${OMIR_OINK_LOCAL_PUBLISH_DIR}/${oink_arch}"
+    # OpenBSD/<rel>/<arch>/oink
+    publish_dir="${OMIR_OINK_LOCAL_PUBLISH_DIR}/${oink_arch}"
 
-	autodie dodir "${OMIR_OINK_LOCAL_PUBLISH_DIR}" 0755 "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}"
-	autodie dodir "${publish_dir}" 0755 "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}"
+    autodie dodir "${OMIR_OINK_LOCAL_PUBLISH_DIR}" 0755 "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}"
+    autodie dodir "${publish_dir}" 0755 "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}"
 
-	for fname in \
-		"miniroot${oink_rel_short}.fs" \
-		"cd${oink_rel_short}.iso"
-	do
-		src="${oink_bdir_arch_ramdisk}/${fname}"
-		dst="${publish_dir}/${fname}"
+    for fname in \
+        "miniroot${oink_rel_short}.fs" \
+        "cd${oink_rel_short}.iso"
+    do
+        src="${oink_bdir_arch_ramdisk}/${fname}"
+        dst="${publish_dir}/${fname}"
 
-		if [ -f "${src}" ]; then
-			einfo "Copying ${fname} to ${publish_dir}"
-			autodie cp -f -- "${src}" "${dst}"
-			autodie chmod -- 0644 "${dst}"
-			if [ -n "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}" ]; then
-				autodie chown -- "${OMIR_OINK_LOCAL_PUBLISH_OWNER}" "${dst}"
-			fi
-		else
-			ewarn "Output file missing: ${src}"
-		fi
-	done
+        if [ -f "${src}" ]; then
+            einfo "Copying ${fname} to ${publish_dir}"
+            autodie cp -f -- "${src}" "${dst}"
+            autodie chmod -- 0644 "${dst}"
+            if [ -n "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}" ]; then
+                autodie chown -- "${OMIR_OINK_LOCAL_PUBLISH_OWNER}" "${dst}"
+            fi
+        else
+            ewarn "Output file missing: ${src}"
+        fi
+    done
 
-	autodie mkindex "${publish_dir}"
-	if [ -n "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}" ]; then
-		autodie chown -- "${OMIR_OINK_LOCAL_PUBLISH_OWNER}" "${publish_dir}/index.txt"
-	fi
+    autodie mkindex "${publish_dir}"
+    if [ -n "${OMIR_OINK_LOCAL_PUBLISH_OWNER-}" ]; then
+        autodie chown -- "${OMIR_OINK_LOCAL_PUBLISH_OWNER}" "${publish_dir}/index.txt"
+    fi
 fi
 
 # hook: fini
